#baseurl: ""
#url: ""

#paginate_path: "/blog/page:num/"
#paginate: 9
#gems: [jekyll-paginate]
#plugins:
#  - jekyll-feed
#  - jekyll-paginate

#address1: "90 Fairground Rd, FL 3290, United States"
#phone_number: "+65 - 3002 56 56 376"
#copyright_text: "© 2022. All Rights Reserved"


# Welcome to Miles Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

favicon:          "/assets/img/favicon.png"


permalink: /blog/:title
post_dirs: false
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate

gems:
  - jekyll-paginate

paginate_path: "/blog/page:num/"

paginate: 4


collections:
  portfolio:
    output: true
  career:
    output: true
    permalink: /career/:path/

# Disqus Comments
disqus:
  enable: false # disque is enabled. Set as false to disable it
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: dexfolio
