# General Settings
title: "Sienna"
favicon: "/assets/img/favicon.png"
name: "Sienna"
description: "Sienna Platform"

# Logo
logo_home_businessconsulting: /Sienna/assets/Sienna-logo-dark.png
logo_white: /Sienna/assets/Sienna-logo-white.png
logo_dark: /Sienna/assets/Sienna-logo-dark.png

# Contact info
contact_settings:
  phone_number: "(+1) 303-275-3000"
  email: "sienna@nrel.gov"
  mailto: "mailto:sienna@nrel.gov"
  address1: "15013 Denver West Parkway Golden, CO 80401"

# Footer info
footer_settings:
  copyright_text: "© 2024. All Rights Reserved"


# Google analytics code
google_analytics:
  enable: false
  key: "UA-664136761-1" # UA-664136761-1

# Social urls
social_settings:
  github: https://github.com/nrel-sienna
